#pragma once
#include "Type.h"

#include <string>

#define BWAPI_ORDERDEF(x) static const Order x(Enum::x) /** ref x */

namespace BWAPI
{
  namespace Orders
  {
    namespace Enum
    {
      enum Enum
      {
        Die,
        Stop,
        Guard,
        PlayerGuard,
        TurretGuard,
        BunkerGuard,
        Move,
        ReaverStop,
        Attack1,
        Attack2,
        AttackUnit,
        AttackFixedRange,
        AttackTile,
        Hover,
        AttackMove,
        InfestedCommandCenter,
        UnusedNothing,
        UnusedPowerup,
        TowerGuard,
        TowerAttack,
        VultureMine,
        StayInRange,
        TurretAttack,
        Nothing,
        Unused_24,
        DroneStartBuild,
        DroneBuild,
        CastInfestation,
        MoveToInfest,
        InfestingCommandCenter,
        PlaceBuilding,
        PlaceProtossBuilding,
        CreateProtossBuilding,
        ConstructingBuilding,
        Repair,
        MoveToRepair,
        PlaceAddon,
        BuildAddon,
        Train,
        RallyPointUnit,
        RallyPointTile,
        ZergBirth,
        ZergUnitMorph,
        ZergBuildingMorph,
        IncompleteBuilding,
        IncompleteMorphing,
        BuildNydusExit,
        EnterNydusCanal,
        IncompleteWarping,
        Follow,
        Carrier,
        ReaverCarrierMove,
        CarrierStop,
        CarrierAttack,
        CarrierMoveToAttack,
        CarrierIgnore2,
        CarrierFight,
        CarrierHoldPosition,
        Reaver,
        ReaverAttack,
        ReaverMoveToAttack,
        ReaverFight,
        ReaverHoldPosition,
        TrainFighter,
        InterceptorAttack,
        ScarabAttack,
        RechargeShieldsUnit,
        RechargeShieldsBattery,
        ShieldBattery,
        InterceptorReturn,
        DroneLand,
        BuildingLand,
        BuildingLiftOff,
        DroneLiftOff,
        LiftingOff,
        ResearchTech,
        Upgrade,
        Larva,
        SpawningLarva,
        Harvest1,
        Harvest2,
        MoveToGas,
        WaitForGas,
        HarvestGas,
        ReturnGas,
        MoveToMinerals,
        WaitForMinerals,
        MiningMinerals,
        Harvest3,
        Harvest4,
        ReturnMinerals,
        Interrupted,
        EnterTransport,
        PickupIdle,
        PickupTransport,
        PickupBunker,
        Pickup4,
        PowerupIdle,
        Sieging,
        Unsieging,
        WatchTarget,
        InitCreepGrowth,
        SpreadCreep,
        StoppingCreepGrowth,
        GuardianAspect,
        ArchonWarp,
        CompletingArchonSummon,
        HoldPosition,
        QueenHoldPosition,
        Cloak,
        Decloak,
        Unload,
        MoveUnload,
        FireYamatoGun,
        MoveToFireYamatoGun,
        CastLockdown,
        Burrowing,
        Burrowed,
        Unburrowing,
        CastDarkSwarm,
        CastParasite,
        CastSpawnBroodlings,
        CastEMPShockwave,
        NukeWait,
        NukeTrain,
        NukeLaunch,
        NukePaint,
        NukeUnit,
        CastNuclearStrike,
        NukeTrack,
        InitializeArbiter,
        CloakNearbyUnits,
        PlaceMine,
        RightClickAction,
        SuicideUnit,
        SuicideLocation,
        SuicideHoldPosition,
        CastRecall,
        Teleport,
        CastScannerSweep,
        Scanner,
        CastDefensiveMatrix,
        CastPsionicStorm,
        CastIrradiate,
        CastPlague,
        CastConsume,
        CastEnsnare,
        CastStasisField,
        CastHallucination,
        Hallucination2,
        ResetCollision,
        ResetHarvestCollision,
        Patrol,
        CTFCOPInit,
        CTFCOPStarted,
        CTFCOP2,
        ComputerAI,
        AtkMoveEP,
        HarassMove,
        AIPatrol,
        GuardPost,
        RescuePassive,
        Neutral,
        ComputerReturn,
        InitializePsiProvider,
        SelfDestructing,
        Critter,
        HiddenGun,
        OpenDoor,
        CloseDoor,
        HideTrap,
        RevealTrap,
        EnableDoodad,
        DisableDoodad,
        WarpIn,
        Medic,
        MedicHeal,
        HealMove,
        MedicHoldPosition,
        MedicHealToIdle,
        CastRestoration,
        CastDisruptionWeb,
        CastMindControl,
        DarkArchonMeld,
        CastFeedback,
        CastOpticalFlare,
        CastMaelstrom,
        JunkYardDog,
        Fatal,
        None,
        Unknown,
        MAX
      };
    }
  }
  /** To get detailed information about what a unit is doing, you can use the Unit::getOrder method, which
   * will return an Order object. Note that a single command, like gather minerals, can consist of several
   * orders ( MoveToMinerals, HarvestMinerals2, MiningMinerals, ReturnMinerals, etc) which will indicate what
   * state the unit is in while executing the command. For information about how to issue commands to units,
   * go to Unit. */
  class Order : public Type<Order, Orders::Enum::Unknown>
  {
    public:
      Order(int id = Orders::Enum::None);

      /** Returns the name of this order. */
      const std::string &getName() const;
      const char *c_str() const;
  };
  namespace Orders
  {
    /** Given the name of an order, getOrder() will return the corresponding order object. */
    Order getOrder(std::string name);

    /** Returns the set of all the Orders. */
    const Order::set& allOrders();

    void init();

    BWAPI_ORDERDEF(Die);
    BWAPI_ORDERDEF(Stop);
    BWAPI_ORDERDEF(Guard);
    BWAPI_ORDERDEF(PlayerGuard);
    BWAPI_ORDERDEF(TurretGuard);
    BWAPI_ORDERDEF(BunkerGuard);
    BWAPI_ORDERDEF(Move);
    BWAPI_ORDERDEF(AttackUnit);
    BWAPI_ORDERDEF(AttackTile);
    BWAPI_ORDERDEF(Hover);
    BWAPI_ORDERDEF(AttackMove);
    BWAPI_ORDERDEF(InfestedCommandCenter);
    BWAPI_ORDERDEF(UnusedNothing);
    BWAPI_ORDERDEF(UnusedPowerup);
    BWAPI_ORDERDEF(TowerGuard);
    BWAPI_ORDERDEF(VultureMine);
    BWAPI_ORDERDEF(Nothing);
    BWAPI_ORDERDEF(CastInfestation);
    BWAPI_ORDERDEF(InfestingCommandCenter);
    BWAPI_ORDERDEF(PlaceBuilding);
    BWAPI_ORDERDEF(CreateProtossBuilding);
    BWAPI_ORDERDEF(ConstructingBuilding);
    BWAPI_ORDERDEF(Repair);
    BWAPI_ORDERDEF(PlaceAddon);
    BWAPI_ORDERDEF(BuildAddon);
    BWAPI_ORDERDEF(Train);
    BWAPI_ORDERDEF(RallyPointUnit);
    BWAPI_ORDERDEF(RallyPointTile);
    BWAPI_ORDERDEF(ZergBirth);
    BWAPI_ORDERDEF(ZergUnitMorph);
    BWAPI_ORDERDEF(ZergBuildingMorph);
    BWAPI_ORDERDEF(IncompleteBuilding);
    BWAPI_ORDERDEF(BuildNydusExit);
    BWAPI_ORDERDEF(EnterNydusCanal);
    BWAPI_ORDERDEF(Follow);
    BWAPI_ORDERDEF(Carrier);
    BWAPI_ORDERDEF(ReaverCarrierMove);
    BWAPI_ORDERDEF(CarrierIgnore2);
    BWAPI_ORDERDEF(Reaver);
    BWAPI_ORDERDEF(TrainFighter);
    BWAPI_ORDERDEF(InterceptorAttack);
    BWAPI_ORDERDEF(ScarabAttack);
    BWAPI_ORDERDEF(RechargeShieldsUnit);
    BWAPI_ORDERDEF(RechargeShieldsBattery);
    BWAPI_ORDERDEF(ShieldBattery);
    BWAPI_ORDERDEF(InterceptorReturn);
    BWAPI_ORDERDEF(BuildingLand);
    BWAPI_ORDERDEF(BuildingLiftOff);
    BWAPI_ORDERDEF(DroneLiftOff);
    BWAPI_ORDERDEF(LiftingOff);
    BWAPI_ORDERDEF(ResearchTech);
    BWAPI_ORDERDEF(Upgrade);
    BWAPI_ORDERDEF(Larva);
    BWAPI_ORDERDEF(SpawningLarva);
    BWAPI_ORDERDEF(Harvest1);
    BWAPI_ORDERDEF(Harvest2);
    BWAPI_ORDERDEF(MoveToGas);
    BWAPI_ORDERDEF(WaitForGas);
    BWAPI_ORDERDEF(HarvestGas);
    BWAPI_ORDERDEF(ReturnGas);
    BWAPI_ORDERDEF(MoveToMinerals);
    BWAPI_ORDERDEF(WaitForMinerals);
    BWAPI_ORDERDEF(MiningMinerals);
    BWAPI_ORDERDEF(Harvest3);
    BWAPI_ORDERDEF(Harvest4);
    BWAPI_ORDERDEF(ReturnMinerals);
    BWAPI_ORDERDEF(Interrupted);
    BWAPI_ORDERDEF(EnterTransport);
    BWAPI_ORDERDEF(PickupIdle);
    BWAPI_ORDERDEF(PickupTransport);
    BWAPI_ORDERDEF(PickupBunker);
    BWAPI_ORDERDEF(Pickup4);
    BWAPI_ORDERDEF(PowerupIdle);
    BWAPI_ORDERDEF(Sieging);
    BWAPI_ORDERDEF(Unsieging);
    BWAPI_ORDERDEF(InitCreepGrowth);
    BWAPI_ORDERDEF(SpreadCreep);
    BWAPI_ORDERDEF(StoppingCreepGrowth);
    BWAPI_ORDERDEF(GuardianAspect);
    BWAPI_ORDERDEF(ArchonWarp);
    BWAPI_ORDERDEF(CompletingArchonSummon);
    BWAPI_ORDERDEF(HoldPosition);
    BWAPI_ORDERDEF(Cloak);
    BWAPI_ORDERDEF(Decloak);
    BWAPI_ORDERDEF(Unload);
    BWAPI_ORDERDEF(MoveUnload);
    BWAPI_ORDERDEF(FireYamatoGun);
    BWAPI_ORDERDEF(CastLockdown);
    BWAPI_ORDERDEF(Burrowing);
    BWAPI_ORDERDEF(Burrowed);
    BWAPI_ORDERDEF(Unburrowing);
    BWAPI_ORDERDEF(CastDarkSwarm);
    BWAPI_ORDERDEF(CastParasite);
    BWAPI_ORDERDEF(CastSpawnBroodlings);
    BWAPI_ORDERDEF(CastEMPShockwave);
    BWAPI_ORDERDEF(NukeWait);
    BWAPI_ORDERDEF(NukeTrain);
    BWAPI_ORDERDEF(NukeLaunch);
    BWAPI_ORDERDEF(NukePaint);
    BWAPI_ORDERDEF(NukeUnit);
    BWAPI_ORDERDEF(CastNuclearStrike);
    BWAPI_ORDERDEF(NukeTrack);
    BWAPI_ORDERDEF(CloakNearbyUnits);
    BWAPI_ORDERDEF(PlaceMine);
    BWAPI_ORDERDEF(RightClickAction);
    BWAPI_ORDERDEF(CastRecall);
    BWAPI_ORDERDEF(Teleport);
    BWAPI_ORDERDEF(CastScannerSweep);
    BWAPI_ORDERDEF(Scanner);
    BWAPI_ORDERDEF(CastDefensiveMatrix);
    BWAPI_ORDERDEF(CastPsionicStorm);
    BWAPI_ORDERDEF(CastIrradiate);
    BWAPI_ORDERDEF(CastPlague);
    BWAPI_ORDERDEF(CastConsume);
    BWAPI_ORDERDEF(CastEnsnare);
    BWAPI_ORDERDEF(CastStasisField);
    BWAPI_ORDERDEF(CastHallucination);
    BWAPI_ORDERDEF(Hallucination2);
    BWAPI_ORDERDEF(ResetCollision);
    BWAPI_ORDERDEF(Patrol);
    BWAPI_ORDERDEF(CTFCOPInit);
    BWAPI_ORDERDEF(CTFCOPStarted);
    BWAPI_ORDERDEF(CTFCOP2);
    BWAPI_ORDERDEF(ComputerAI);
    BWAPI_ORDERDEF(AtkMoveEP);
    BWAPI_ORDERDEF(HarassMove);
    BWAPI_ORDERDEF(AIPatrol);
    BWAPI_ORDERDEF(GuardPost);
    BWAPI_ORDERDEF(RescuePassive);
    BWAPI_ORDERDEF(Neutral);
    BWAPI_ORDERDEF(ComputerReturn);
    BWAPI_ORDERDEF(SelfDestructing);
    BWAPI_ORDERDEF(Critter);
    BWAPI_ORDERDEF(HiddenGun);
    BWAPI_ORDERDEF(OpenDoor);
    BWAPI_ORDERDEF(CloseDoor);
    BWAPI_ORDERDEF(HideTrap);
    BWAPI_ORDERDEF(RevealTrap);
    BWAPI_ORDERDEF(EnableDoodad);
    BWAPI_ORDERDEF(DisableDoodad);
    BWAPI_ORDERDEF(WarpIn);
    BWAPI_ORDERDEF(Medic);
    BWAPI_ORDERDEF(MedicHeal);
    BWAPI_ORDERDEF(HealMove);
    BWAPI_ORDERDEF(MedicHealToIdle);
    BWAPI_ORDERDEF(CastRestoration);
    BWAPI_ORDERDEF(CastDisruptionWeb);
    BWAPI_ORDERDEF(CastMindControl);
    BWAPI_ORDERDEF(DarkArchonMeld);
    BWAPI_ORDERDEF(CastFeedback);
    BWAPI_ORDERDEF(CastOpticalFlare);
    BWAPI_ORDERDEF(CastMaelstrom);
    BWAPI_ORDERDEF(JunkYardDog);
    BWAPI_ORDERDEF(Fatal);
    BWAPI_ORDERDEF(None);
    BWAPI_ORDERDEF(Unknown);
  };
}
